name: azkar
description: A new Flutter project.

publish_to: 'none'

version: 1.2.0+22

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  adhan: ^2.0.0-nullsafety.2
  assets_audio_player: ^3.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  flutter_compass: ^0.7.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^1.1.6
  get_it: ^7.2.0
  hijri: ^3.0.0
  internet_connection_checker: ^1.0.0+1
  page_transition: ^2.0.9
  shared_preferences: ^2.0.15
  persian_number_utility: ^1.1.4
  geolocator: ^9.0.2
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.2
  mockito: ^5.4.4
  build_runner: ^2.4.8
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.1
  android_alarm_manager_plus: ^3.0.4
  syncfusion_flutter_pdfviewer: ^24.1.46
  bloc: ^8.1.3
  gif: ^2.3.0
  flutter_qiblah: ^2.2.0
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.11
  flutter_launcher_icons: "^0.13.1"

dependency_overrides:
  uuid: ^4.1.0  # Override to force compatibility

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo-t.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter_native_splash:
  android: true
  ios: true
  web: false
  fullscreen: false
  color: '#ffffff'
  image: 'assets/images/splash-logo.png'
  android_12:
    color: '#ffffff'
    image: 'assets/images/splash-logo.png'

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/adhan.wav
    - assets/json/
    - assets/images/
    - assets/json/metas.json
    - assets/json/quran.json

  fonts:
    - family: Changa
      fonts:
        - asset: assets/fonts/Changa.ttf
    - family: ArslanWessam
      fonts:
        - asset: assets/fonts/Arslan-Wessam-B.ttf
    - family: HafsSmart
      fonts:
        - asset: assets/fonts/HafsSmart_08.ttf
